import fs from 'node:fs/promises';
import {launch,pageFor,capture,tool,gesture,saveJSON,root,outDir} from './harness.mjs';
const selected=process.argv.slice(2),results=selected.length?JSON.parse(await fs.readFile((process.env.AUDIT_OUT?root+'/'+process.env.AUDIT_OUT:root+'/docs/audit')+'/contracts-results.json','utf8').catch(()=> '[]').catch(()=> '[]')):[];
const browser=await launch();
const paint=page=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
const option=(page,label)=>page.locator('.cmp-tool-header .option').filter({has:page.locator('.label').getByText(label,{exact:true})});
async function run(id,title,fn,profile='standard'){if(selected.length&&!selected.includes(id))return;let page,row={id,title,kind:'contract',scope:'独立浏览器的真实 UI 或业务模块合同；OTools 文件服务为内存替身'};try{page=await pageFor(browser,profile);page.setDefaultTimeout(6000);Object.assign(row,await fn(page));row.status=row.status??(row.pass?'通过':'失败');if(page.auditErrors.length)row.pageErrors=page.auditErrors;}catch(e){row.status='未验证';row.error=e.message;row.note='脚本或前置条件异常，不直接算产品缺陷，须人工归因。';}finally{if(page)await page.close();}const at=results.findIndex(r=>r.id===id);if(at<0)results.push(row);else results[at]=row;await saveJSON('contracts-results.json',results);console.log(id,row.status,row.error??row.note??'');}
async function nested(page){return page.evaluate(()=>{const {E,D,pixel}=window.A,d=E.api.doc,root=D.createGroupLayer('外层组'),sub=D.createGroupLayer('内层组'),leaf=pixel('叶子',16,16,[220,30,50,255]),dest=D.createGroupLayer('目标组');sub.parentId=root.id;leaf.parentId=sub.id;root.expanded=sub.expanded=dest.expanded=true;d.layers.push(leaf,sub,root,dest);d.activeLayerId=root.id;E.api.invalidate();window.nestedIds={root:root.id,sub:sub.id,leaf:leaf.id,dest:dest.id};return window.nestedIds;});}
try{
 for(const [dialog,id,title,expected]of [['canvasSize','FLOW-canvas-width','画布大小只改宽度不应篡改高度',32],['imageSize','FLOW-image-aspect','非正方形图像改宽度应保持比例',40]])await run(id,title,async page=>{await page.evaluate(dialog=>{window.A.E.api.doc.height=32;window.A.E.openDialog(dialog);},dialog);const form=page.locator('.el-dialog:visible'),input=form.locator('input[type=number]');await input.nth(0).fill('80');await input.nth(0).press('Tab');const uiHeight=await input.nth(1).inputValue();await form.getByRole('button',{name:'确定',exact:true}).click();const after=await capture(page);return{pass:after.width===80&&after.height===expected,actual:[after.width,after.height],uiHeight,expected:[80,expected]};});
 await run('FLOW-marquee-feather','框选羽化必须保留非空覆盖率并生成软边',async page=>{await tool(page,'marquee',{feather:3});await gesture(page,[[24,24],[40,40]]);const a=await capture(page);return{pass:a.selection?.count>0&&a.selection.gray,selection:a.selection};});
 await run('FLOW-brush-shift','Shift 点击连接上次画笔端点为直线',async page=>{await tool(page,'brush',{size:2,hardness:1,opacity:1});await gesture(page,[[22,22]],{click:true});await gesture(page,[[42,42]],{click:true,keys:['Shift']});return page.evaluate(()=>{const p=window.A.E.api.activeLayer().pixels;const mid=Array.from(p.data.slice((16*p.width+16)*4,(16*p.width+16)*4+4));return{pass:mid[0]<5&&mid[1]>250&&mid[2]<5,midpoint:mid,expected:[0,255,0,255]};});});
 await run('FLOW-group-move','移动组必须连同组内像素内容一起移动',async page=>{await page.evaluate(()=>{const {E,D}=window.A,d=E.api.doc,g=D.createGroupLayer('移动组');g.transform.size=[64,64];d.layers[1].parentId=g.id;d.layers.push(g);d.activeLayerId=g.id;E.api.invalidate();});await tool(page,'move',{snap:false});const b=await capture(page);await gesture(page,[[32,32],[40,38]]);const a=await capture(page);return{pass:a.layers[1].transform.origin[0]===24&&a.layers[1].transform.origin[1]===22,before:b.layers.map(l=>({name:l.name,t:l.transform})),after:a.layers.map(l=>({name:l.name,t:l.transform})),compositeChanged:a.composite.hash!==b.composite.hash};});
 await run('FLOW-multiselect-move','多选两个图层后移动应同时移动选中的图层',async page=>{await page.locator('.layer-row').filter({hasText:'背景'}).click();await page.locator('.layer-row').filter({hasText:'前景'}).click({modifiers:['Shift']});await page.evaluate(()=>window.A.E.api.setToolOption('snap',false));const b=await capture(page);await gesture(page,[[32,32],[40,38]]);const a=await capture(page);return{pass:a.layers.every((l,i)=>l.transform.origin[0]===b.layers[i].transform.origin[0]+8),before:b.layers.map(l=>l.transform.origin),after:a.layers.map(l=>l.transform.origin),selectedRows:await page.locator('.layer-row.selected').count()};});
 for(const duplicate of [false,true])await run('FLOW-nested-drag-'+duplicate,duplicate?'Alt 拖拽复制组保留后代层级':'真实拖拽嵌套组保留后代层级',async page=>{const ids=await nested(page);if(duplicate)await page.keyboard.down('Alt');await page.locator('.layer-row').filter({has:page.locator('.name').getByText('外层组',{exact:true})}).dragTo(page.locator('.layer-row').filter({has:page.locator('.name').getByText('目标组',{exact:true})}));if(duplicate)await page.keyboard.up('Alt');const layers=await page.evaluate(()=>window.A.E.api.doc.layers.map(l=>({id:l.id,name:l.name,parent:l.parentId})));const movedRoot=duplicate?layers.find(l=>l.name.startsWith('外层')&&l.id!==ids.root):layers.find(l=>l.id===ids.root),movedSub=duplicate?layers.find(l=>l.name.startsWith('内层')&&l.id!==ids.sub):layers.find(l=>l.id===ids.sub),movedLeaf=duplicate?layers.find(l=>l.name.startsWith('叶子')&&l.id!==ids.leaf):layers.find(l=>l.id===ids.leaf);return{pass:!!movedRoot&&movedRoot.parent===ids.dest&&movedSub?.parent===movedRoot.id&&movedLeaf?.parent===movedSub?.id,layers,ids};});
 await run('FLOW-nested-command','嵌套移动命令独立验证：仅根节点换父组',async page=>{const ids=await nested(page);await page.evaluate(ids=>window.A.E.commands.run('moveLayerTo',{ids:[ids.root],referenceId:ids.dest,position:'inside',duplicate:false}),ids);const a=await capture(page);return{pass:a.layers.find(l=>l.id===ids.root)?.parent===ids.dest&&a.layers.find(l=>l.id===ids.sub)?.parent===ids.root&&a.layers.find(l=>l.id===ids.leaf)?.parent===ids.sub,layers:a.layers.map(l=>({name:l.name,id:l.id,parent:l.parent})),ids};});
 for(const alt of [false,true])await run('FLOW-selection-move-'+alt,alt?'Alt 拖动复制选区内像素，保留原图层其余像素':'移动工具只移动选区内像素而非整层',async page=>{await page.evaluate(()=>{const {E,P}=window.A;const m=P.createMask(64,64,0);for(let y=24;y<32;y++)for(let x=24;x<32;x++)m.data[y*64+x]=255;E.api.doc.selection={...m,outline:null};E.api.setToolOption('snap',false);});const b=await capture(page);await gesture(page,[[27,27],[35,27]],{keys:alt?['Alt']:[]});const a=await capture(page);return{pass:JSON.stringify(a.layers[1].transform)===JSON.stringify(b.layers[1].transform)&&a.layers[1].pixels.hash!==b.layers[1].pixels.hash,before:b.layers[1],after:a.layers[1],note:'上游有选区像素移动/复制分支，本地应区别于整层平移。'};});
 await run('FLOW-nudge-history','方向键微调一次只增加一条历史且一次撤销恢复',async page=>{const b=await capture(page);await page.keyboard.press('ArrowRight');const a=await capture(page);await page.keyboard.press('Control+KeyZ');const undo=await capture(page);return{pass:a.history===b.history+1&&undo.layers[1].transform.origin[0]===b.layers[1].transform.origin[0],history:[b.history,a.history,undo.history],origins:[b.layers[1].transform.origin,a.layers[1].transform.origin,undo.layers[1].transform.origin]};});
 await run('FLOW-warp-shift','Meta+Shift 拖动扭曲角点应锁轴',async page=>{await page.evaluate(()=>window.A.E.api.setToolOption('snap',false));await gesture(page,[[16,16],[8,12]],{keys:['Meta','Shift']});const warp=(await capture(page)).layers[1].transform.warp;return{pass:!!warp&&(Math.abs(warp[0].x)<.0001||Math.abs(warp[0].y)<.0001),warp,note:'Meta 用于触发当前实现的扭曲；Windows Ctrl 单独已有失败用例。'};});
 await run('FLOW-shape-edit','形状绘制后修改描边宽度仍可编辑已有形状',async page=>{await tool(page,'shape');await gesture(page,[[20,20],[40,40]]);const b=await page.evaluate(()=>({shape:window.A.E.api.activeLayer().shape,hash:window.A.hash(window.A.E.api.activeLayer().pixels.data)}));await option(page,'描边宽度').locator('input').fill('6');await option(page,'描边宽度').locator('input').press('Tab');const a=await page.evaluate(()=>({shape:window.A.E.api.activeLayer().shape,hash:window.A.hash(window.A.E.api.activeLayer().pixels.data),option:window.A.E.api.option('strokeWidth',0)}));return{pass:a.shape.strokeWidth===6&&b.hash!==a.hash,before:b,after:a};});
 await run('FLOW-gradient-edit','渐变绘制后反向控件应更新已有渐变',async page=>{await tool(page,'gradient',{dither:false});await gesture(page,[[20,20],[44,40]]);const b=await capture(page);await option(page,'反向').locator('.el-checkbox').click();const a=await capture(page);return{pass:a.layers[1].pixels.hash!==b.layers[1].pixels.hash,before:b.layers[1].pixels.hash,after:a.layers[1].pixels.hash,option:await page.evaluate(()=>window.A.E.api.option('reverse',false)),note:'当前工具只保存拖动瞬态起止点，没有持久可编辑渐变元数据。'};});
 await run('FLOW-mask-delete','编辑蒙版时图层面板删除按钮只删除蒙版',async page=>{await page.evaluate(()=>window.A.E.commands.run('addMask'));const b=await capture(page);await page.locator('.layers-panel .panel-bar').getByRole('button',{name:'删除',exact:true}).click();const a=await capture(page);return{pass:a.layers.length===b.layers.length&&!a.layers.find(l=>l.id===b.layers[1].id)?.mask,before:b.layers.map(l=>({id:l.id,mask:l.mask})),after:a.layers.map(l=>({id:l.id,mask:l.mask}))};});
 await run('FLOW-open-image-dirty','导入位图应标脏并能一次撤销',async page=>{const b=await capture(page);await page.evaluate(()=>window.A.E.commands.run('openImage'));const a=await capture(page);await page.evaluate(()=>window.A.E.commands.run('undo'));const undo=await capture(page);return{pass:a.dirty&&a.history===b.history+1&&undo.layers.length===b.layers.length,before:{layers:b.layers.length,dirty:b.dirty,history:b.history},after:{layers:a.layers.length,dirty:a.dirty,history:a.history},undo:{layers:undo.layers.length,dirty:undo.dirty,history:undo.history}};});
 for(const [command,path]of [['openImage','/audit/input.png'],['openRaw','/audit/input.dng'],['openPsd','/audit/input.psd'],['openComp','/audit/project.comp']])await run('FLOW-start-'+command,'欢迎页直接打开 / '+command,async page=>{const result=await page.evaluate(async({command,path})=>{window.auditHost.openPath=path;let error;try{await window.A.E.commands.run(command);}catch(e){error=e.message;}return{error,state:window.A.state(),messages:window.auditHost.messages};},{command,path});return{pass:result.state.documents>0,...result};},'empty');
 await run('FLOW-jpeg-format','JPEG 快捷键打开后格式必须为 JPEG 并可预览',async page=>{await page.keyboard.press('Control+Alt+KeyS');const dialog=page.locator('.el-dialog:visible');const format=await dialog.locator('.el-select__selected-item').first().textContent();return{pass:format?.includes('JPEG')&&await dialog.locator('img,canvas').count()>0,format,previewNodes:await dialog.locator('img,canvas').count(),note:'格式 payload 与导出预览分别检查。'};});
 await run('FLOW-effects-ui','六种图层效果均有颜色/大小/强度参数编辑入口',async page=>{await page.evaluate(()=>{window.A.E.api.activeLayer().effects={stroke:{enabled:true,size:3,color:[0,255,0],opacity:1},shadow:{enabled:true,angle:45,distance:5,blur:3,color:[0,0,0],opacity:1},colorOverlay:{enabled:true,color:[0,0,255],opacity:.5},innerShadow:{enabled:true,angle:45,distance:3,blur:2,color:[0,0,0],opacity:1},outerGlow:{enabled:true,size:3,color:[0,255,0],opacity:1},innerGlow:{enabled:true,size:3,color:[0,255,0],opacity:1}};window.A.E.api.invalidate();});const section=page.locator('.props section').filter({has:page.getByRole('heading',{name:'图层效果',exact:true})});const controls=await section.locator('input').evaluateAll(es=>es.map(e=>({type:e.type,value:e.value})));const editors=controls.filter(x=>['number','range','color'].includes(x.type));return{pass:editors.length>=6,status:editors.length>=6?'部分通过':'未实现',controls,text:await section.innerText()};});
 await run('FLOW-filter-preview','破坏性滤镜具有参数和确认/取消实时预览流程',async page=>{const b=await capture(page);await page.evaluate(()=>window.A.E.commands.run('filterVignette'));const a=await capture(page);return{pass:!!a.dialog&&a.layers[1].pixels.hash===b.layers[1].pixels.hash,dialog:a.dialog,history:[b.history,a.history],pixelChanged:a.layers[1].pixels.hash!==b.layers[1].pixels.hash,note:'直接落盘修改不等于带确认/取消的实时预览面板。'};});
 await run('FLOW-grid-enable','网格设置中的启用开关应立即显示网格',async page=>{await page.evaluate(()=>window.A.E.openDialog('gridSettings'));await page.locator('.el-dialog:visible .el-switch').click();const flags=await page.evaluate(()=>({doc:window.A.E.api.doc.grid.enabled,ui:window.A.E.api.ui.grid}));return{pass:flags.doc&&flags.ui,flags};});
 await run('FLOW-grid-subdivisions','网格 subdivisions 改动应产生细分线',async page=>{await page.evaluate(()=>{const {E}=window.A;E.api.ui.grid=true;E.api.ui.transformControls=false;E.api.doc.grid.enabled=true;E.api.doc.grid.spacing=32;E.api.doc.grid.subdivisions=0;E.api.invalidate();});await paint(page);const hash=()=>page.evaluate(()=>{const c=document.querySelectorAll('.cmp-stage canvas')[1];return window.A.hash(c.getContext('2d').getImageData(0,0,c.width,c.height).data);});const b=await hash();await page.evaluate(()=>{window.A.E.api.doc.grid.subdivisions=4;window.A.E.api.invalidate();});await paint(page);const a=await hash();return{pass:a!==b,before:b,after:a};});
 await run('FLOW-move-controls','移动工具头部显示变换控件开关实际控制显示',async page=>{await paint(page);const hash=()=>page.evaluate(()=>{const c=document.querySelectorAll('.cmp-stage canvas')[1];return window.A.hash(c.getContext('2d').getImageData(0,0,c.width,c.height).data);});const b=await hash();await option(page,'显示变换控件').locator('.el-checkbox').click();await paint(page);const a=await hash();return{pass:a!==b,before:b,after:a,flags:await page.evaluate(()=>({ui:window.A.E.api.ui.transformControls,option:window.A.E.api.option('showControls',true)}))};});
 await run('FLOW-guide-move','画布内已有参考线可以拖动调整位置',async page=>{await page.evaluate(()=>{window.A.E.api.doc.guides=[{id:'guide-test',axis:'vertical',position:10}];window.A.E.api.ui.transformControls=false;window.A.E.api.invalidate();});await gesture(page,[[10,32],[14,32]]);const a=await page.evaluate(()=>window.A.E.api.doc.guides);return{pass:a[0].position===14,actual:a};});
 await run('FLOW-guide-history','从标尺新建参考线可撤销',async page=>{await page.evaluate(()=>{window.A.E.api.ui.rulers=true;window.A.E.api.invalidate();});await paint(page);const r=await page.locator('.cmp-stage').boundingBox();await page.mouse.move(r.x+150,r.y+8);await page.mouse.down();await page.mouse.move(r.x+150,r.y+150,{steps:5});await page.mouse.up();const beforeUndo=await page.evaluate(()=>({guides:window.A.E.api.doc.guides,dirty:window.A.E.api.doc.dirty,history:window.A.E.currentHistory().position}));await page.evaluate(()=>window.A.E.commands.run('undo'));const after=await page.evaluate(()=>window.A.E.api.doc.guides);return{pass:beforeUndo.guides.length===1&&after.length===0,beforeUndo,after};});
 await run('FLOW-opacity-digits','单数字与连续两位数字正确设置图层透明度',async page=>{await page.keyboard.press('Digit5');const fifty=await page.evaluate(()=>window.A.E.api.activeLayer().opacity);await page.keyboard.press('Digit7');await page.keyboard.press('Digit5');const seventyFive=await page.evaluate(()=>window.A.E.api.activeLayer().opacity);return{pass:fifty===.5&&seventyFive===.75,fifty,seventyFive,expected:[.5,.75]};});
 await run('FLOW-tab-tool','Tab 循环当前分组工具而非仅转移焦点',async page=>{await tool(page,'brush');await page.evaluate(()=>document.activeElement?.blur());const b=await capture(page);await page.keyboard.press('Tab');const a=await capture(page);return{pass:a.tool!==b.tool,before:b.tool,after:a.tool,activeElement:await page.evaluate(()=>document.activeElement?.outerHTML.slice(0,180))};});
 await run('FLOW-command-palette','Ctrl+F 命令面板入口',async page=>{await page.keyboard.press('Control+KeyF');const a=await capture(page);const count=await page.locator('[role=dialog]:visible,input[type=search]:visible').count();return{pass:count>0,status:count?'部分通过':'未实现',dialog:a.dialog,candidateNodes:count,note:'上游 1.4.6 README 的 Command Palette，不是浏览器内置查找。'};});
 await run('FLOW-canvas-only','F 切换仅画布模式',async page=>{const b=await page.locator('.cmp-toolbar').isVisible();await page.keyboard.press('KeyF');const a=await page.locator('.cmp-toolbar').isVisible();return{pass:b&&!a,status:b&&!a?'通过':'未实现',toolbarBefore:b,toolbarAfter:a};});
 await run('FLOW-label-scrub','拖动数值标签擦洗值，而不是必须拖输入框',async page=>{await tool(page,'brush',{size:40});const label=option(page,'大小').locator('.label'),r=await label.boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(r.x+r.width/2+30,r.y+r.height/2,{steps:5});await page.mouse.up();const value=await page.evaluate(()=>window.A.E.api.option('size',0));return{pass:value!==40,actual:value,expected:'标签拖拽30px后数值改变'};});
 await run('FLOW-layer-context','图层行右键出现图层操作菜单',async page=>{await page.locator('.layer-row').filter({hasText:'前景'}).click({button:'right'});const menuCount=await page.locator('.el-dropdown-menu:visible').count();return{pass:menuCount>0,status:menuCount?'通过':'未实现',menuCount,note:'存在 ⋯ 左键菜单不等于右键菜单。'};});
 await run('FLOW-toolbar-longpress','工具栏长按弹出同组工具选择',async page=>{const button=page.getByTitle('画笔（B）',{exact:true}),r=await button.boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.waitForTimeout(800);const menus=await page.locator('[role=menu]:visible,.tool-flyout:visible').count();await page.mouse.up();return{pass:menus>0,status:menus?'部分通过':'未实现',menus,note:'当前工具全量展开可点击，但未实现声明的长按组内弹出。'};});
 await run('FLOW-panel-dock','浮动/拖动/缩放/左侧停靠与持久化',async page=>{const panel=page.locator('.dock-panel').filter({has:page.locator('.dock-header .title').getByText('图层',{exact:true})});await panel.getByTitle('浮动',{exact:true}).click();const floating=page.locator('.float-panel').filter({has:page.locator('.float-header .title').getByText('图层',{exact:true})});const h=await floating.locator('.float-header .title').boundingBox();await page.mouse.move(h.x+15,h.y+8);await page.mouse.down();await page.mouse.move(h.x-80,h.y-40,{steps:5});await page.mouse.up();const moved=await page.evaluate(()=>({...window.A.Panels.panelStates.layers.float}));const res=await floating.locator('.float-resize').boundingBox();await page.mouse.move(res.x+3,res.y+3);await page.mouse.down();await page.mouse.move(res.x+53,res.y+53,{steps:5});await page.mouse.up();const resized=await page.evaluate(()=>({...window.A.Panels.panelStates.layers.float}));await floating.getByTitle('停靠到左侧',{exact:true}).click();const area=await page.evaluate(()=>window.A.Panels.panelStates.layers.area);await page.waitForTimeout(600);await page.reload({waitUntil:'networkidle'});const persisted=await page.evaluate(async()=>{const m=await import('/src/composables/usePanels.ts');return m.panelStates.layers.area;});return{pass:moved.x!==660&&resized.width>moved.width&&area==='left'&&persisted==='left',moved,resized,area,persisted};});
 await run('FLOW-panel-edge','浮动面板拖到窗口右边缘松开自动停靠',async page=>{await page.evaluate(()=>window.A.Panels.toggleFloat('layers'));const f=page.locator('.float-panel').filter({has:page.locator('.float-header .title').getByText('图层',{exact:true})});const h=await f.locator('.float-header .title').boundingBox();await page.mouse.move(h.x+12,h.y+8);await page.mouse.down();await page.mouse.move(1420,400,{steps:8});await page.mouse.up();return page.evaluate(()=>({pass:window.A.Panels.panelStates.layers.area==='right',area:window.A.Panels.panelStates.layers.area}));});
 await run('FLOW-panel-doubleclick','停靠面板双击标题切换为浮动（原计划说明）',async page=>{await page.locator('.dock-header .title').getByText('图层',{exact:true}).dblclick();return page.evaluate(()=>({pass:window.A.Panels.panelStates.layers.area==='float',area:window.A.Panels.panelStates.layers.area,collapsed:window.A.Panels.panelStates.layers.collapsed}));});
 await run('FLOW-theme-persistence','主题切换并重载保留',async page=>{await page.evaluate(()=>window.A.E.commands.run('setTheme','light'));await page.waitForTimeout(150);const before=await page.evaluate(()=>document.documentElement.className);await page.reload({waitUntil:'networkidle'});const after=await page.evaluate(()=>document.documentElement.className);return{pass:before===after&&before.includes('light'),before,after};});
 await run('COLOR-roundtrips','sRGB/线性、HSL、HSV、Lab 数值往返',async page=>page.evaluate(async()=>{const c=await import('/src/core/color.ts'),samples=[[0,0,0],[255,255,255],[255,0,0],[20,80,160],[120,90,200]],checks=[];for(const rgb of samples){const hsl=c.rgbToHsl(...rgb),hsv=c.rgbToHsv(...rgb),lab=c.rgbToLab(...rgb);for(const [name,x]of [['HSL',c.hslToRgb(hsl.h,hsl.s,hsl.l)],['HSV',c.hsvToRgb(hsv.h,hsv.s,hsv.v)],['Lab',c.labToRgb(lab.l,lab.a,lab.b)]])checks.push({name,rgb,out:x,error:Math.max(...[x.r,x.g,x.b].map((v,i)=>Math.abs(v-rgb[i])))});for(const value of rgb)checks.push({name:'sRGB',value,error:Math.abs(c.linearToSrgb(c.srgbToLinear(value))-value)});}return{pass:checks.every(x=>x.error<1),checks};}));
 for(const width of [1440,960])await run('UI-layout-'+width,'工作区布局可见性 / '+width,async page=>{await page.setViewportSize({width,height:900});await paint(page);const bounds=await page.evaluate(()=>({page:[document.documentElement.scrollWidth,innerWidth],stage:(()=>{const r=document.querySelector('.cmp-stage').getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height};})(),body:[document.body.scrollWidth,document.body.clientWidth]}));await fs.mkdir(outDir+'/screenshots',{recursive:true});await page.screenshot({path:outDir+'/screenshots/layout-'+width+'.png'});return{pass:bounds.page[0]<=bounds.page[1]+1&&bounds.stage.width>200&&bounds.stage.height>200,bounds,screenshot:'screenshots/layout-'+width+'.png',note:'仅代表这些分辨率结构不溢出，不替代 OTools 宿主/DPI/字体外观验收。'};});
}finally{await browser.close();}
