import fs from 'node:fs/promises';
import {launch,pageFor,capture,tool,gesture,saveJSON,root} from './harness.mjs';
const selected=process.argv.slice(2),results=selected.length?JSON.parse(await fs.readFile((process.env.AUDIT_OUT?root+'/'+process.env.AUDIT_OUT:root+'/docs/audit')+'/edges-results.json','utf8').catch(()=> '[]')):[],browser=await launch();
async function run(id,title,fn){if(selected.length&&!selected.includes(id))return;let p,r={id,title,kind:'edge',scope:'独立 Chromium；真实 UI 或业务 API，宿主文件服务为内存替身'};try{p=await pageFor(browser);p.setDefaultTimeout(6000);Object.assign(r,await fn(p));r.status=r.status??(r.pass?'通过':'失败');}catch(e){r.status='未验证';r.error=e.message;}finally{if(p)await p.close();}const at=results.findIndex(x=>x.id===id);if(at<0)results.push(r);else results[at]=r;await saveJSON('edges-results.json',results);console.log(id,r.status,r.error??'');}
try{
 await run('EDGE-eyedropper-layer-size','吸管当前图层取样也应按取样大小平均',async p=>{await p.evaluate(()=>{const {E}=window.A,l=E.api.activeLayer();l.pixels.data.fill(0);for(let i=0;i<l.pixels.data.length;i+=4)l.pixels.data.set([200,0,0,255],i);l.pixels.data.set([0,200,0,255],(16*32+16)*4);E.api.invalidate();});await tool(p,'eyedropper',{sample:'layer',size:1});await gesture(p,[[32,32]],{click:true});const one=await p.evaluate(()=>[...window.A.E.api.foreground]);await p.evaluate(()=>window.A.E.api.setToolOption('size',9));await gesture(p,[[32,32]],{click:true});const nine=await p.evaluate(()=>[...window.A.E.api.foreground]);return{pass:JSON.stringify(one)!==JSON.stringify(nine),one,nine};});
 await run('EDGE-eyedropper-layer-transform','吸管当前图层取样正确映射缩放图层坐标',async p=>{await p.evaluate(()=>{window.A.E.api.activeLayer().transform.size=[16,16];window.A.E.api.invalidate();});await tool(p,'eyedropper',{sample:'layer',size:1});await gesture(p,[[21,21]],{click:true});return p.evaluate(()=>{const {E,C}=window.A,d=E.api.doc,l=E.api.activeLayer(),b=C.compositeDocument({...d,layers:[l]},64,64).buffer,expected=Array.from(b.data.slice((21*64+21)*4,(21*64+21)*4+3)),actual=[...E.api.foreground];return{pass:actual.every((v,i)=>Math.abs(v-expected[i])<=1),actual,expected};});});
 await run('EDGE-snap-layer-edge','移动时图层边缘靠近参考线应吸附，不只检测鼠标点',async p=>{await p.evaluate(()=>{const {E}=window.A;E.api.doc.guides=[{id:'edge',axis:'vertical',position:61}];E.api.doc.snap={guides:true,grid:false,layers:false,document:false};E.api.setViewport({zoom:4});E.api.setToolOption('snap',true);});await gesture(p,[[32,32],[44,32]]);const origin=(await capture(p)).layers[1].transform.origin;return{pass:origin[0]+32===61,origin,rightEdge:origin[0]+32,expectedEdge:61};});
 await run('EDGE-snap-scaled-target','缩放后的目标层边缘坐标不可再次缩放',async p=>p.evaluate(async()=>{const {E}=window.A,d=E.api.doc,l=E.api.activeLayer();l.transform.origin=[40,16];l.transform.size=[16,16];d.layers=[l];d.snap={guides:false,grid:false,layers:true,document:false};E.api.setViewport({zoom:4});const {snapPoint}=await import('/src/core/engine/snapping.ts');const r=snapPoint(E.api,{x:55.5,y:60});return{pass:r.point.x===56,point:r.point,expectedX:56};}));
 await run('EDGE-history-jump','点击历史列表较早条目跳转到该历史状态',async p=>{await p.evaluate(async()=>{for(let i=0;i<4;i++)await window.A.E.commands.run('newLayer');});const count=await p.locator('.history .entry').count();await p.locator('.history .entry').first().click();const a=await capture(p);return{pass:a.history===0,entries:count,historyAfterClick:a.history,expected:0};});
 await run('EDGE-colors-swap-button','颜色面板交换按钮保留原来的两种颜色',async p=>{const b=await p.evaluate(()=>({fg:[...window.A.E.api.foreground],bg:[...window.A.E.api.background]}));await p.locator('.side-panels').getByRole('button',{name:'交换 (X)',exact:true}).click();const a=await p.evaluate(()=>({fg:[...window.A.E.api.foreground],bg:[...window.A.E.api.background]}));return{pass:JSON.stringify(a.fg)===JSON.stringify(b.bg)&&JSON.stringify(a.bg)===JSON.stringify(b.fg),before:b,after:a};});
 await run('EDGE-colors-hex-sync','吸管/快捷键修改前景色后 HEX 输入显示同步',async p=>{await p.keyboard.press('KeyX');const hex=await p.locator('.side-panels input').inputValue();const color=await p.evaluate(()=>[...window.A.E.api.foreground]);const expected='#'+color.map(c=>c.toString(16).padStart(2,'0')).join('');return{pass:hex.toLowerCase().replace('#','')===expected.replace('#',''),hex,color,expected};});
 await run('EDGE-chinese-anchor','画布锚点选择项已中文化',async p=>{await p.evaluate(()=>window.A.E.openDialog('canvasSize'));await p.locator('.el-dialog:visible .el-select').click();await p.locator('.el-select-dropdown__item:visible').first().waitFor();const labels=await p.locator('.el-select-dropdown__item:visible').allTextContents();return{pass:labels.length===9&&labels.every(s=>/[\u4e00-\u9fff]/.test(s)),labels};});
 await run('EDGE-merge-group-key','Ctrl+E 选中组时合并整个组',async p=>{await p.evaluate(()=>window.A.E.commands.run('group',window.A.E.api.doc.layers.map(l=>l.id)));const b=await capture(p);await p.keyboard.press('Control+KeyE');const a=await capture(p);return{pass:a.layers.length===1&&a.layers[0].kind==='pixel'&&a.composite.hash===b.composite.hash,before:b.layers.map(l=>l.kind),after:a.layers.map(l=>l.kind)};});
 await run('EDGE-lock-guides','Ctrl+Alt+; 切换参考线锁定',async p=>{await p.keyboard.press('Control+Alt+Semicolon');const fields=await p.evaluate(()=>({snap:window.A.E.api.doc.snap,guideKeys:Object.keys(window.A.E.api.doc).filter(k=>/lock/i.test(k))}));return{pass:false,status:'未实现',fields,note:'没有参考线锁定模型/命令/快捷键；不把图层 locked 当作参考线锁定。'};});
 await run('EDGE-shortcut-conflict','快捷键冲突应阻止/明确选择，不保存后静默遮蔽',async p=>{const result=await p.evaluate(()=>{const {S}=window.A;const chord=S.shortcutItems.find(i=>i.id==='tool.brush').chord;const warning=S.setShortcut('file.save',{...chord});return{warning,saved:S.shortcutItems.find(i=>i.id==='file.save').chord,matched:S.findShortcut(chord)?.id};});return{pass:result.saved.key!=='b',...result,note:'当前允许冲突保存，提示“两条命令会同时触发”，但 findShortcut 只返回第一条。'};});
 await run('EDGE-global-color-picker','前景色色块可打开完整颜色选择器',async p=>{await p.locator('.side-panels .chip.fg').click();await p.waitForTimeout(100);const visible=await p.locator('.el-color-picker__panel:visible').count();return{pass:visible>0,status:visible?'部分通过':'未实现',visible,note:'主颜色面板只有 HEX 输入。文字工具的颜色控件有选择器，但并非全局前景色入口。'};});
 await run('EDGE-merge-multi-key','Ctrl+E 合并非相邻多选层而不吞掉未选中层',async p=>{const middleId=await p.evaluate(()=>{const {E,pixel}=window.A;const middle=E.api.doc.layers[1].id;E.api.doc.layers.push(pixel('第三层',24,24,[40,220,90,255]));E.api.invalidate();return middle;});await p.locator('.layer-row').filter({hasText:'背景'}).click();await p.locator('.layer-row').filter({hasText:'第三层'}).click({modifiers:['Shift']});await p.keyboard.press('Control+KeyE');const a=await capture(p);return{pass:a.layers.length===2&&a.layers.some(l=>l.id===middleId),middleId,layers:a.layers.map(l=>({id:l.id,name:l.name}))};});
 await run('EDGE-temporary-hand','空格临时抓手平移且不绘画，松开保留原工具',async p=>{await tool(p,'brush');const b=await capture(p);await gesture(p,[[24,24],[36,32]],{keys:['Space']});const a=await capture(p);return{pass:a.tool==='brush'&&a.viewport.centerX!==b.viewport.centerX&&a.layers[1].pixels.hash===b.layers[1].pixels.hash,before:b.viewport,after:a.viewport,tool:a.tool};});
 await run('EDGE-crop-selection','切换裁剪时采用已有选区边界，Enter 应用',async p=>{await p.evaluate(()=>{const {E,P}=window.A,m=P.createMask(64,64,0);for(let y=20;y<40;y++)for(let x=20;x<40;x++)m.data[y*64+x]=255;E.api.doc.selection={...m,outline:null};});await tool(p,'crop');await p.evaluate(()=>document.activeElement?.blur());await p.keyboard.press('Enter');const a=await capture(p);return{pass:a.width===20&&a.height===20,size:[a.width,a.height]};});
 await run('EDGE-crop-symmetric','Alt 裁剪以起点为中心对称扩展',async p=>{await tool(p,'crop');await gesture(p,[[24,24],[38,40]],{keys:['Alt']});await p.keyboard.press('Enter');const a=await capture(p);return{pass:a.width===28&&a.height===32,actual:[a.width,a.height],expected:[28,32]};});
 await run('EDGE-crop-snap','裁剪框靠近参考线时吸附',async p=>{await tool(p,'crop');await p.evaluate(()=>{const {E}=window.A;E.api.doc.guides=[{id:'crop-guide',axis:'vertical',position:42}];E.api.doc.snap={guides:true,grid:false,layers:false,document:false};E.api.setViewport({zoom:4});});await gesture(p,[[20,20],[40.8,40]]);await p.keyboard.press('Enter');const a=await capture(p);return{pass:a.width===22,actualWidth:a.width,expectedWidth:22};});
 await run('EDGE-crop-cancel','Escape 取消裁剪，再按 Enter 不改变画布',async p=>{await tool(p,'crop');const b=await capture(p);await gesture(p,[[20,20],[40,40]]);await p.keyboard.press('Escape');await p.keyboard.press('Enter');const a=await capture(p);return{pass:a.width===b.width&&a.height===b.height&&a.composite.hash===b.composite.hash,size:[a.width,a.height]};});
 await run('EDGE-selection-booleans','框选替换、Shift加选、Alt减选、Shift+Alt交集',async p=>{await tool(p,'marquee',{feather:0});const counts=[];await gesture(p,[[20,20],[30,30]]);counts.push((await capture(p)).selection.count);await gesture(p,[[25,20],[35,30]],{keys:['Shift']});counts.push((await capture(p)).selection.count);await gesture(p,[[28,20],[38,30]],{keys:['Alt']});counts.push((await capture(p)).selection.count);await gesture(p,[[20,20],[25,30]],{keys:['Shift','Alt']});counts.push((await capture(p)).selection.count);return{pass:counts.join()==='100,150,80,50',counts,expected:[100,150,80,50]};});
 // 补齐没有菜单覆盖的命令，并实际验证状态结果。
 for(const command of ['toggleVisibility','toggleLock','mergeSelection','mergeGroup','deleteMask','toggleMask','maskTarget','wandSelect','transformSelection','copyLayer','openRecent','applyRawDevelop'])await run('CMD-'+command,'命令合同 / '+command,async p=>p.evaluate(async command=>{const {E,D,P}=window.A,d=E.api.doc;let payload,extra={};if(['deleteMask','toggleMask','maskTarget'].includes(command))await E.commands.run('addMask');if(command==='mergeSelection')payload=d.layers.map(l=>l.id);if(command==='mergeGroup')await E.commands.run('group',d.layers.map(l=>l.id));if(command==='transformSelection'){d.selection={...P.createMask(64,64,0),outline:null};d.selection.data[20*64+20]=255;payload={x:2,y:3};}if(command==='openRecent')payload='/audit/project.comp';if(command==='applyRawDevelop'){window.auditHost.openPath='/audit/input.dng';await E.commands.run('openRaw');const layer=E.api.activeLayer();payload={layerId:layer.id,raw:layer.rawData,settings:{...layer.rawData.settings,exposure:-1}};}const before=window.A.state(),locked=E.api.activeLayer()?.locked;await E.commands.run(command,payload);let after=window.A.state(),pass=false;
 if(command==='toggleVisibility')pass=after.layers[1].visible!==before.layers[1].visible;
 if(command==='toggleLock')pass=E.api.activeLayer().locked!==locked;
 if(command==='mergeSelection'||command==='mergeGroup')pass=after.layers.length===1&&after.composite.hash===before.composite.hash;
 if(command==='deleteMask')pass=!after.layers[1].mask;
 if(command==='toggleMask')pass=after.layers[1].mask.enabled===false;
 if(command==='maskTarget')pass=after.layers[1].mask.target==='image';
 if(command==='wandSelect')pass=after.selection?.count>0;
 if(command==='transformSelection')pass=E.api.doc.selection.data[23*64+22]===255&&after.selection.count===1;
 if(command==='copyLayer'){await E.commands.run('paste');after=window.A.state();pass=after.layers.length===before.layers.length+1&&after.layers.at(-1).pixels.hash===before.layers.at(-1).pixels.hash;}
 if(command==='openRecent')pass=after.documents===before.documents+1&&after.width===16;
 if(command==='applyRawDevelop')pass=after.layers.at(-1).pixels.hash!==before.layers.at(-1).pixels.hash&&after.dirty;
 return{pass,before,after,...extra};},command));
 await run('CMD-unwatchComp','停止工程监视后不再读取目录',async p=>{await p.evaluate(async()=>{const {E}=window.A;E.api.doc.packagePath='/audit/project.comp';window.auditHost.readCount=0;const read=window.otools.readHostFile;window.otools.readHostFile=async path=>{window.auditHost.readCount++;return read(path);};await E.commands.run('watchComp');});await p.waitForTimeout(850);await p.evaluate(()=>window.A.E.commands.run('unwatchComp'));const before=await p.evaluate(()=>window.auditHost.readCount);await p.waitForTimeout(900);const after=await p.evaluate(()=>window.auditHost.readCount);return{pass:before>0&&after===before,before,after};});
 await run('CMD-flattenClipboard','flattenClipboard 命令有实际实现',async p=>{const source=await fs.readFile(root+'/src/composables/commands.ts','utf8');const empty=/case 'flattenClipboard': break;/.test(source);return{pass:!empty,status:empty?'未实现':'未验证',empty,note:'无界面绑定的空分支；不是一个可宣称完成的功能。'};});
}finally{await browser.close();}
