import {launch,pageFor,tiffFixture,tool,gesture,saveJSON} from './harness.mjs';
const browser=await launch(),results=[];
async function run(id,title,fn,arg){let page,r;try{page=await pageFor(browser);const v=await fn(page,arg);r={id,title,kind:'format',...v,status:v.pass?'通过':v.unverified?'未实测':'失败'};}catch(e){r={id,title,kind:'format',status:'失败',error:e.message};}finally{if(page)await page.close();}results.push(r);await saveJSON('formats-results.json',results);console.log(id,r.status,r.error??r.detail??'');}
const fromBytes=(p,base64)=>p.evaluate(async base64=>{const b=Uint8Array.from(atob(base64),x=>x.charCodeAt(0));const value=await window.A.I.decodeImageBytes(b.buffer);return window.A.summary(value);},base64);
try{
 for(const format of ['png','jpeg','webp'])await run('FORMAT-'+format,'浏览器位图导入 / '+format,async(p,format)=>{const r=await p.evaluate(async format=>{const c=document.createElement('canvas');c.width=c.height=16;const ctx=c.getContext('2d');ctx.fillStyle='rgb(200,60,20)';ctx.fillRect(0,0,16,16);const blob=await new Promise(resolve=>c.toBlob(resolve,'image/'+format,.9));const b=await window.A.I.decodeImageBytes(await blob.arrayBuffer());return window.A.summary(b);},format);return{pass:r.width===16&&r.height===16&&Math.abs(r.first[0]-200)<=3,actual:r,scope:'浏览器标准编码器生成样本，未覆盖ICC/EXIF全部变体'};},format);
 const bmp=Buffer.alloc(70);bmp.write('BM');bmp.writeUInt32LE(70,2);bmp.writeUInt32LE(54,10);bmp.writeUInt32LE(40,14);bmp.writeInt32LE(2,18);bmp.writeInt32LE(2,22);bmp.writeUInt16LE(1,26);bmp.writeUInt16LE(24,28);for(let y=0;y<2;y++)for(let x=0;x<2;x++)bmp.set([56,34,12],54+y*8+x*3);
 await run('FORMAT-bmp','BMP 24bit 标准样本',async p=>{const r=await fromBytes(p,bmp.toString('base64'));return{pass:r.width===2&&r.height===2&&r.first.join()==='12,34,56,255',actual:r};});
 await run('FORMAT-gif','GIF 首帧解码',async p=>{const r=await fromBytes(p,'R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==');return{pass:r.width===1&&r.height===1,actual:r,scope:'单帧标准样本，不证明动画逐帧功能'};});
 await run('FORMAT-svg','SVG 标准矩形栅格化',async p=>{const r=await fromBytes(p,Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="2" height="2"><rect width="2" height="2" fill="#0c2238"/></svg>').toString('base64'));return{pass:r.width===2&&r.height===2&&r.first.join()==='12,34,56,255',actual:r};});
 for(const options of [{bitDepth:8},{bitDepth:16},{big:true},{compression:5},{compression:32773},{tile:true}])await run('FORMAT-tiff-'+JSON.stringify(options),'TIFF / '+JSON.stringify(options),async p=>{const r=await fromBytes(p,tiffFixture(options));return{pass:r.width===16&&r.height===16&&r.first[0]===30,actual:r,expectedFirst:30,scope:'独立构造的有效经典TIFF；不包含ICC/多页/浮点变体'};});
 await run('FORMAT-tiff-unsupported-rejection','未支持 TIFF 压缩不应静默返回黑图',async p=>{let result,error;try{result=await fromBytes(p,tiffFixture({compression:7}));}catch(e){error=e.message;}return{pass:!!error,actual:result,error,scope:'负例：压缩标志7，不调用真实JPEG压缩数据，不宣称检验LJPEG解码质量'};});
 for(const compression of [1,5,32773])await run('FORMAT-raw-'+compression,'RAW TIFF容器压缩 / '+compression,async p=>{const r=await p.evaluate(({a,b})=>{const decode=s=>window.A.R.decodeRaw(Uint8Array.from(atob(s),x=>x.charCodeAt(0)).buffer);const base=decode(a),sample=decode(b);return{base:window.A.summary(base.data),sample:window.A.summary(sample.data)};},{a:tiffFixture({raw:true}),b:tiffFixture({raw:true,compression})});return{pass:r.base.hash===r.sample.hash,actual:r,scope:'合成CFA/DNG结构；真实相机文件未测'};});
 for(const name of ['CR2','NEF','ARW','ORF','PEF','SRW','RW2','CR3','RAF','AVIF','HEIC','HEIF','PSB'])await run('FORMAT-real-'+name,'真实 '+name+' 样本',async()=>({pass:false,unverified:true,detail:'仓库无此真实样本；不能以扩展名列表、同容器合成样本或浏览器可能支持代替验证'}));
 await run('PSD-basic-roundtrip','PSD 基本图层颜色往返',async p=>{return p.evaluate(()=>{const {E,PSD,C,hash}=window.A,d=E.api.doc,before=hash(C.compositeDocument(d).buffer.data),bytes=PSD.exportPsd(d),after=PSD.importPsd(bytes,'重开').document;return{pass:before===hash(C.compositeDocument(after).buffer.data),before,after:hash(C.compositeDocument(after).buffer.data),names:after.layers.map(l=>l.name),scope:'插件与ag-psd的往返，不是Photoshop实机验收'};});});
 for(const feature of ['rotation','placed-mask','group-mask','effects','text'])await run('PSD-roundtrip-'+feature,'PSD 往返 / '+feature,async p=>p.evaluate(feature=>{const {E,D,P,C,PSD,hash}=window.A,d=E.api.doc,l=E.api.activeLayer();if(feature==='rotation')l.transform.rotation=35;if(feature==='placed-mask')l.mask={pixels:P.createMask(8,8,255),enabled:true,linked:false,placement:{x:24,y:24,width:8,height:8},target:'image',inverted:false};if(feature==='group-mask'){const g=D.createGroupLayer('带蒙版组');D.addLayerMask(g,64,64).data.fill(128);l.parentId=g.id;d.layers.push(g);}if(feature==='effects')l.effects={colorOverlay:{enabled:true,color:[0,255,0],opacity:1}};if(feature==='text')l.text={content:'hello',fontName:'Arial',fontSize:12,color:[0,0,0],align:'left',tracking:0,lineSpacing:0,boxSize:null,bold:false,italic:false};const before=hash(C.compositeDocument(d).buffer.data),after=PSD.importPsd(PSD.exportPsd(d),'重开').document,afterHash=hash(C.compositeDocument(after).buffer.data);return{pass:before===afterHash&&(feature!=='text'||after.layers.some(l=>l.text)),before,after:afterHash,metadataKept:after.layers.some(l=>feature==='text'?l.text:feature==='effects'?l.effects:l.mask),scope:'本插件往返，不代替外部软件验证'};},feature));
 for(const feature of ['Curves','Gradient Map'])await run('COMP-native-'+feature,'上游 .comp 调整字段 / '+feature,async p=>p.evaluate(async feature=>{const H=window.auditHost,m=H.manifest;const a={id:'33333333-3333-4333-8333-333333333333',name:'原版调整',isVisible:true,transform:{origin:[0,0],size:[16,16],rotation:0,flipX:false,flipY:false,sampling:'Nearest'},adjustment:{kind:feature}};if(feature==='Curves')a.adjustment.curves={channel:'RGB',channels:Array.from({length:4},()=>[{x:0,y:0},{x:128,y:210},{x:255,y:255}])};else a.adjustment.gradientMapSettings={shadows:{red:1,green:0,blue:0},highlights:{red:0,green:0,blue:1},reversed:false};m.layers.push(a);H.writeManifest();try{const d=await window.A.IO.loadCompProject('/audit/project.comp');const output=window.A.summary(window.A.C.compositeDocument(d).buffer);return{pass:output.visible>0&&output.first.slice(0,3).some(x=>x>0),output};}catch(e){return{pass:false,error:e.message};}},feature));
 await run('COMP-shape-native-save','形状保存的 ID 和字段满足原版 .comp 合约',async p=>{await tool(p,'shape');await gesture(p,[[20,20],[40,40]]);return p.evaluate(async()=>{await window.A.IO.saveCompProject(window.A.E.api.doc,'/audit/project.comp');const m=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(window.auditHost.files['/audit/project.comp/manifest.json']),x=>x.charCodeAt(0)))),l=m.layers.at(-1);return{pass:/^[a-f0-9]{8}-[a-f0-9-]{27}$/i.test(l.id)&&typeof l.shape.red==='number'&&['Rectangle','Ellipse','Line'].includes(l.shape.kind),layerId:l.id,shape:l.shape,scope:'按原版 UUID / ShapeKind / RGB 字段合约验证'};});});
 await run('COMP-exact-clipping-source','上游显式剪贴源引用不能被改指向相邻层',async p=>p.evaluate(async()=>{const H=window.auditHost,m=H.manifest,ids=[m.layers[0].id,'33333333-3333-4333-8333-333333333333','44444444-4444-4444-8444-444444444444'];const png=(color,half)=>{const c=document.createElement('canvas');c.width=c.height=16;const ctx=c.getContext('2d');ctx.fillStyle=color;ctx.fillRect(0,0,half?8:16,16);return c.toDataURL().split(',')[1];};m.layers=ids.map((id,i)=>({id,name:['源','中间','目标'][i],isVisible:true,imageFile:id+'.png',maskSourceID:i===2?ids[0]:null,transform:{origin:[0,0],size:[16,16],rotation:0,flipX:false,flipY:false,sampling:'Nearest'}}));ids.forEach((id,i)=>H.put('/audit/project.comp/images/'+id+'.png',png(['red','blue','lime'][i],i===0)));H.writeManifest();const d=await window.A.IO.loadCompProject('/audit/project.comp');const data=window.A.C.compositeDocument(d).buffer.data;await window.A.IO.saveCompProject(d,'/audit/project.comp');const saved=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(H.files['/audit/project.comp/manifest.json']),x=>x.charCodeAt(0))));return{pass:data[(8*16+12)*4+2]===255&&saved.layers[2].maskSourceID===ids[0],rightPixel:Array.from(data.slice((8*16+12)*4,(8*16+12)*4+4)),savedSource:saved.layers[2].maskSourceID,expectedSource:ids[0]};}));
 await run('SECURITY-id-path','拒绝会在保存时逃逸临时目录的图层 ID',async p=>p.evaluate(async()=>{const H=window.auditHost;H.manifest.layers[0].id='../../audit-escape';H.manifest.activeLayerID='../../audit-escape';H.writeManifest();let rejected=false;try{const d=await window.A.IO.loadCompProject('/audit/project.comp');await window.A.IO.saveCompProject(d,'/audit/project.comp');}catch(e){rejected=true;}const escaped=H.writes.filter(w=>w.path==='/audit/AUDIT-ESCAPE.png');return{pass:rejected&&escaped.length===0,rejected,escapedWrites:escaped,scope:'仅内存文件系统；没有写入真实磁盘'};}));
 for(const type of ['resource-path','duplicate-id','parent-cycle','version','oversized-transform'])await run('VALIDATION-'+type,'.comp 校验 / '+type,async p=>p.evaluate(async type=>{const H=window.auditHost,m=H.manifest;if(type==='resource-path')m.layers[0].imageFile='../bad.png';if(type==='duplicate-id')m.layers.push({...m.layers[0]});if(type==='parent-cycle'){m.layers[0].isGroup=true;delete m.layers[0].imageFile;m.layers[0].parentID=m.layers[0].id;}if(type==='version')m.version=999;if(type==='oversized-transform')m.layers[0].transform.size=[1e9,1e9];H.writeManifest();let rejected=false,error;try{await window.A.IO.loadCompProject('/audit/project.comp');}catch(e){rejected=true;error=e.message;}return{pass:rejected,rejected,error,scope:type==='oversized-transform'?'只执行加载校验，没有合成/分配巨大图像':'内存文件系统'};},type));
}finally{await browser.close();}
