import fs from 'node:fs/promises';
import {launch,pageFor,capture,tool,gesture,saveJSON,root} from './harness.mjs';
const selected=process.argv.slice(2),results=selected.length?JSON.parse(await fs.readFile((process.env.AUDIT_OUT?root+'/'+process.env.AUDIT_OUT:root+'/docs/audit')+'/parity-results.json','utf8').catch(()=> '[]').catch(()=> '[]')):[],browser=await launch();
async function run(id,title,fn){if(selected.length&&!selected.includes(id))return;let page,r={id,title,kind:'parity',scope:'按固定上游源码语义验证本地实现；不是上游 macOS 实机执行'};try{page=await pageFor(browser);page.setDefaultTimeout(6000);Object.assign(r,await fn(page));r.status=r.status??(r.pass?'通过':'失败');if(page.auditErrors.length)r.pageErrors=page.auditErrors;}catch(e){r.status='未验证';r.error=e.message;r.note='先检查脚本前置条件，不能把超时直接判为产品错误。';}finally{if(page)await page.close();}const at=results.findIndex(x=>x.id===id);if(at<0)results.push(r);else results[at]=r;await saveJSON('parity-results.json',results);console.log(id,r.status,r.error??'');}
async function selection(page){await page.evaluate(()=>{const {E,P}=window.A,m=P.createMask(64,64,0);for(let y=24;y<32;y++)for(let x=24;x<32;x++)m.data[y*64+x]=255;E.api.doc.selection={...m,outline:null};E.api.invalidate();});}
try{
 for(let digit=0;digit<=9;digit++)await run('PARITY-opacity-'+digit,'原版透明度数字键 '+digit,async p=>{await p.evaluate(()=>window.A.E.api.activeLayer().opacity=.25);await p.keyboard.press('Digit'+digit);const actual=await p.evaluate(()=>window.A.E.api.activeLayer().opacity),expected=digit===0?1:digit/10;return{pass:actual===expected,actual,expected};});
 for(const [direction,axis,sign]of [['Left',0,-1],['Right',0,1],['Up',1,-1],['Down',1,1]])for(const shift of [false,true])for(const ctrl of [false,true])await run('PARITY-arrow-'+direction+'-'+shift+'-'+ctrl,(ctrl?'移动选区像素':'微移图层')+' '+direction+' '+(shift?10:1)+'px',async p=>{if(ctrl)await selection(p);const before=await capture(p);await p.keyboard.press((ctrl?'Control+':'')+(shift?'Shift+':'')+'Arrow'+direction);const after=await capture(p),a=after.layers[1],b=before.layers[1];return{pass:ctrl?JSON.stringify(a.transform)===JSON.stringify(b.transform)&&a.pixels.hash!==b.pixels.hash:a.transform.origin[axis]===b.transform.origin[axis]+sign*(shift?10:1),before:{transform:b.transform,pixels:b.pixels.hash},after:{transform:a.transform,pixels:a.pixels.hash},historyDelta:after.history-before.history};});
 await run('PARITY-ctrl-t','Ctrl+T 应开始变换，不应新增反相调整层',async p=>{const b=await capture(p);await p.keyboard.press('Control+KeyT');const a=await capture(p);return{pass:a.layers.length===b.layers.length&&a.tool==='move',before:b.layers.length,after:a.layers.map(l=>({kind:l.kind,name:l.name})),dialog:a.dialog};});
 for(const [key,name]of [['M','Curves'],['L','Levels'],['U','Hue/Saturation']])await run('PARITY-adjust-'+name,'原版 Ctrl+'+key+' 打开破坏性 '+name+' 编辑器',async p=>{const b=await capture(p);await p.keyboard.press('Control+Key'+key);const a=await capture(p);return{pass:!!a.dialog&&a.layers.length===b.layers.length,before:b.layers.length,after:a.layers.map(l=>({kind:l.kind,name:l.name})),dialog:a.dialog,note:'本地新增同名调整层不是原版 Image 菜单的破坏性编辑流程。'};});
 await run('PARITY-jpeg-shortcut','原版 Ctrl+Shift+Alt+S 打开 JPEG 预览',async p=>{await p.keyboard.press('Control+Shift+Alt+KeyS');const a=await capture(p);return{pass:a.dialog==='exportDialog',dialog:a.dialog,note:'本地注册为 Ctrl+Alt+S，且现有对话框默认 PNG。'};});
 await run('PARITY-shift-delete','原版 Shift+Delete 进入内容识别而非直接清空像素',async p=>{await selection(p);const b=await capture(p);await p.keyboard.press('Shift+Delete');const a=await capture(p);return{pass:!!a.dialog&&a.layers[1].pixels.visible===b.layers[1].pixels.visible,before:b.layers[1].pixels,after:a.layers[1].pixels,dialog:a.dialog};});
 await run('PARITY-delete','Delete 删除当前图层',async p=>{const b=await capture(p);await p.keyboard.press('Delete');const a=await capture(p);return{pass:a.layers.length===b.layers.length-1,before:b.layers.length,after:a.layers.length};});
 await run('PARITY-layer-via-copy','有选区时 Ctrl+J 仅复制选区内像素',async p=>{await selection(p);await p.keyboard.press('Control+KeyJ');const a=await capture(p);return{pass:a.layers.length===3&&a.layers[2].pixels.visible===64,created:a.layers[2],expectedVisiblePixels:64};});
 for(const [toolId,key,field]of [['marquee','M','shape'],['lasso','L','mode'],['wand','W','tool'],['blur','R','tool']])await run('PARITY-cycle-'+toolId,'重复 '+key+' 循环 '+toolId+' 的模式',async p=>{await tool(p,toolId);const get=()=>p.evaluate(field=>field==='tool'?window.A.E.api.toolId:window.A.E.api.option(field,''),field);const b=await get();await p.evaluate(()=>document.activeElement?.blur());await p.keyboard.press('Key'+key);const a=await get();return{pass:a!==b,before:b,after:a};});
 for(const [key,sign]of [['Minus',-1],['Equal',1]])await run('PARITY-blend-cycle-'+sign,'Shift+'+(sign<0?'-':'+')+' 循环图层混合模式',async p=>{await p.keyboard.press('Shift+'+key);const actual=await p.evaluate(()=>window.A.E.api.activeLayer().blendMode);return{pass:actual!=='Normal',actual};});
 await run('PARITY-shape-cycle','Shift+U 循环形状类型',async p=>{await tool(p,'shape');const b=await p.evaluate(()=>window.A.E.api.option('kind',''));await p.evaluate(()=>document.activeElement?.blur());await p.keyboard.press('Shift+KeyU');const a=await p.evaluate(()=>window.A.E.api.option('kind',''));return{pass:a!==b,before:b,after:a};});
 await run('PARITY-select-tool','A 键切换独立选择工具',async p=>{await p.keyboard.press('KeyA');const a=await capture(p);return{pass:a.tool==='select',tool:a.tool,status:a.tool==='select'?'通过':'未实现'};});
 for(const [direction,field,sign]of [['Left','tracking',-1],['Right','tracking',1],['Up','lineSpacing',-1],['Down','lineSpacing',1]])for(const shift of [false,true])await run('PARITY-text-'+direction+'-'+shift,'文字 Alt+'+(shift?'Shift+':'')+direction+' 修改 '+field,async p=>{await tool(p,'type',{fontSize:10,tracking:20,lineSpacing:20});await gesture(p,[[20,20]],{click:true});await p.getByRole('textbox',{name:'编辑画布文字'}).fill('AB');const before=await p.evaluate(field=>window.A.E.api.activeLayer().text[field],field);await p.keyboard.press('Alt+'+(shift?'Shift+':'')+'Arrow'+direction);const after=await p.evaluate(field=>window.A.E.api.activeLayer().text[field],field);return{pass:after===before+sign*(shift?10:1),before,after,expected:before+sign*(shift?10:1)};});
 await run('PARITY-mask-link-ui','蒙版链接/解除链接 UI 入口',async p=>{await p.evaluate(()=>window.A.E.commands.run('addMask'));const controls=await p.locator('.props').innerText();const has=/链接|解除链接|linked/i.test(controls);return{pass:has,status:has?'部分通过':'未实现',text:controls,note:'数据模型有 linked 和 placement；此项只判断用户能否操作链接状态。'};});
 await run('PARITY-mask-transform','选中独立蒙版后移动应只改变蒙版位置',async p=>{await p.evaluate(()=>{const {E,D}=window.A,l=E.api.activeLayer();D.addLayerMask(l,64,64);l.mask.linked=false;l.mask.placement={x:0,y:0,width:64,height:64};l.mask.target='mask';E.api.setToolOption('snap',false);E.api.invalidate();});const b=await capture(p);await gesture(p,[[32,32],[40,38]]);const a=await p.evaluate(()=>({transform:window.A.E.api.activeLayer().transform,mask:window.A.E.api.activeLayer().mask.placement}));return{pass:JSON.stringify(a.transform)===JSON.stringify(b.layers[1].transform)&&a.mask.x===8&&a.mask.y===6,before:b.layers[1].transform,after:a};});
 await run('PARITY-outline-move','选区工具在已有选区内拖动只移动轮廓',async p=>{await tool(p,'marquee');await gesture(p,[[24,24],[40,40]]);const b=await capture(p);await gesture(p,[[28,28],[32,32]]);const a=await capture(p);return{pass:a.selection?.count===b.selection?.count&&a.selection.hash!==b.selection.hash,before:b.selection,after:a.selection};});
 await run('PARITY-adjust-selection','已存在调整层不随临时选区变化改变外观',async p=>{await p.evaluate(()=>window.A.E.commands.run('addAdjustment','Invert'));const b=await capture(p);await selection(p);const a=await capture(p);return{pass:b.composite.hash===a.composite.hash,before:b.composite.hash,after:a.composite.hash,note:'对照上游合成路径：已落地调整层应由其图层蒙版限制，临时选区用于编辑预览。'};});
 await run('PARITY-psd-before-apply','PSD 转换报告在应用前确认，可取消导入',async p=>{const b=await capture(p);await p.evaluate(()=>{window.auditHost.openPath='/audit/input.psd';return window.A.E.commands.run('openPsd');});const during=await capture(p);await p.locator('.el-dialog:visible').getByRole('button',{name:'关闭',exact:true}).click();const after=await capture(p);return{pass:during.documents===b.documents&&after.documents===b.documents,documents:[b.documents,during.documents,after.documents],dialog:during.dialog};});
 await run('PARITY-cross-doc-copy','复制整组到另一个标签页保留层级、像素和独立 ID',async p=>{const r=await p.evaluate(async()=>{const {E,D}=window.A;const original=E.api.doc;await E.commands.run('group',original.layers.map(l=>l.id));const ids=original.layers.map(l=>l.id);await E.commands.run('copy');const target=D.createDocument(64,64,'目标工程');E.openDocument(target);await E.commands.run('paste');const d=E.api.doc;return{pass:d.layers.length===3&&d.layers.filter(l=>l.kind!=='group').every(l=>l.parentId===d.activeLayerId)&&d.layers.every(l=>!ids.includes(l.id)),source:original.layers.map(l=>({id:l.id,parent:l.parentId})),target:d.layers.map(l=>({id:l.id,parent:l.parentId,hash:l.pixels?window.A.hash(l.pixels.data):null}))};});return r;});
 await run('PARITY-cross-doc-drag','拖动图层到另一个项目标签转移/复制到目标项目',async p=>{await p.evaluate(()=>{const {E,D}=window.A;const d=D.createDocument(64,64,'目标工程');E.openDocument(d);E.selectDocument(0);});await p.locator('.layer-row').filter({hasText:'前景'}).dragTo(p.locator('.tabs .tab').filter({hasText:'目标工程'}));const docs=await p.evaluate(()=>window.A.E.documents.value.map(d=>({name:d.name,layers:d.layers.length})));return{pass:docs[1].layers>0,documents:docs};});
 await run('PARITY-layer-lock-ui','图层面板有锁定/解锁入口',async p=>{const text=await p.locator('.layers-panel').innerText();const hints=await p.locator('.layers-panel [title]').evaluateAll(es=>es.map(e=>e.title));const found=/锁定|解锁|lock/i.test(text+' '+hints.join(' '));return{pass:found,status:found?'部分通过':'未实现',text,hints,note:'toggleLock 命令和锁定渲染保护存在，但不等于有界面入口。'};});
 await run('PARITY-raw-filter-entry','普通 PNG 图层可以进入 Camera Raw Filter',async p=>{const raw=JSON.parse(await fs.readFile(root+'/docs/audit/catalog-static.json','utf8'));const found=raw.menus.filter(m=>/raw/i.test(m.label)&&m.action.command!=='openRaw');return{pass:found.length>0,status:found.length?'部分通过':'未实现',entries:found,note:'现有入口只导入 RAW 文件，不是对普通图层的 Camera Raw Filter。'};});
 await run('PARITY-psd-large-fallback','大 PSD 图层超出内存时裁到画布的降级路径',async p=>{const source=await fs.readFile(root+'/src/io/psd.ts','utf8');return{pass:false,status:'未实现',hasMemoryBudget:/recommendedBudget|memoryBudget|deviceMemory/.test(source),note:'PSD 导入先完整 readPsd/useImageData，没有上游按预算裁层降级路径；为避免耗尽内存未分配巨型样本。'};});
 await run('PARITY-pixel-grid-toggle','用户可以开关像素网格',async p=>{const c=JSON.parse(await fs.readFile(root+'/docs/audit/catalog-static.json','utf8'));const entries=c.menus.filter(m=>/像素网格/.test(m.label));return{pass:entries.length>0,status:entries.length?'部分通过':'未实现',entries,note:'渲染器有高倍率像素网格，但 CanvasStage 固定 showPixelGrid:true，无用户开关。'};});
}finally{await browser.close();}
