import {test,expect} from '@playwright/test';
// @ts-ignore 共用隔离的内存宿主，不触碰真实用户工程。
import {pageFor,tool,gesture} from '../../scripts/audit/harness.mjs';

const values=[128,128+1/257,128+2/257,128+3/257];

test('16位缓冲、克隆、翻转和缩放保留相邻16位灰阶',async({browser})=>{
 const page=await pageFor(browser);try{const r=await page.evaluate(values=>{const {P}= (window as any).A,b=P.createBuffer(4,1,undefined,16);for(let x=0;x<4;x++)b.data.set([values[x],values[x],values[x],255],x*4);const c=P.cloneBuffer(b),f=P.flipBuffer(b,true,false),s=P.resizeBuffer(b,4,1);return{type:b.data.constructor.name,depth:b.bitDepth,bytes:P.bufferBytes(b),clone:Array.from(c.data).filter((_,i)=>i%4===0),flip:Array.from(f.data).filter((_,i)=>i%4===0),scaled:Array.from(s.data).filter((_,i)=>i%4===0)};},values);expect(r.type).toBe('Float32Array');expect(r.depth).toBe(16);expect(r.bytes).toBe(64);r.clone.forEach((v:any,i:number)=>expect(v).toBeCloseTo(values[i]!,4));r.scaled.forEach((v:any,i:number)=>expect(v).toBeCloseTo(values[i]!,4));r.flip.forEach((v:any,i:number)=>expect(v).toBeCloseTo(values[3-i]!,4));}finally{await page.close();}
});

for(const kind of ['Levels','Curves','Exposure','Hue/Saturation','Gradient Map','Gaussian Blur','Motion Blur'])test('16位合成与调整保留亚8位差异 '+kind,async({browser})=>{
 const page=await pageFor(browser);try{const r=await page.evaluate(({kind,values})=>{const {D,P,C}= (window as any).A,d=D.createDocument(8,8,'16位',16),b=P.createBuffer(8,8,undefined,16);for(let y=0;y<8;y++)for(let x=0;x<8;x++){const v=values[x%4];b.data.set([v,v,v,255],(y*8+x)*4);}const l=D.createPixelLayer('微小色阶',b);l.transform.sampling='Nearest';d.layers=[l];const a=D.createAdjustmentLayer(kind,d);if(kind==='Exposure')a.adjustment.exposureSettings.exposure=.25;if(kind==='Gaussian Blur')a.adjustment.blurRadius=.6;if(kind==='Motion Blur')a.adjustment.motionDistance=2;d.layers.push(a);const out=C.compositeDocument(d).buffer;return{depth:out.bitDepth,type:out.data.constructor.name,rgb:Array.from(out.data).filter((_,i)=>i%4===0),invalid:Array.from(out.data).some((n:any)=>!Number.isFinite(n)||n<0||n>255)};},{kind,values});expect(r.depth).toBe(16);expect(r.type).toBe('Float32Array');expect(r.invalid).toBe(false);const inside=r.rgb.slice(24,32) as number[];expect(new Set(inside.map(v=>Math.round(v*257))).size).toBeGreaterThan(1);expect(inside.some(v=>Math.abs(v-Math.round(v))>0.0005)).toBe(true);}finally{await page.close();}
});

test('16位PNG编码/解码与工程保存重开保持每个16位分量',async({browser})=>{
 const page=await pageFor(browser);try{const r=await page.evaluate(async values=>{const {D,P,E,I,IO}= (window as any).A,d=D.createDocument(4,1,'高位深',16),b=P.createBuffer(4,1,undefined,16);for(let i=0;i<4;i++)b.data.set([values[i],32.5,255,128+2/257],i*4);d.layers=[D.createPixelLayer('16位层',b)];d.activeLayerId=d.layers[0].id;E.openDocument(d);const blob=await I.encodeImage(b,{format:'png',quality:1,scale:1,background:[255,255,255]}),bytes=new Uint8Array(await blob.arrayBuffer()),decoded=await I.decodeImageBytes(bytes.buffer);await IO.saveCompProject(d,'/audit/project.comp');const loaded=await IO.loadCompProject('/audit/project.comp');return{pngBits:bytes[24],decodedDepth:decoded.bitDepth,decoded:Array.from(decoded.data),projectDepth:loaded.bitDepth,project:Array.from(loaded.layers[0].pixels.data),original:Array.from(b.data)};},values);expect(r.pngBits).toBe(16);expect(r.decodedDepth).toBe(16);expect(r.projectDepth).toBe(16);r.original.forEach((v:any,i:number)=>{expect(Math.abs(r.decoded[i]-v)).toBeLessThanOrEqual(1/257);expect(Math.abs(r.project[i]-v)).toBeLessThanOrEqual(1/257);});}finally{await page.close();}
});

test('16位图层填充、滤镜撤销重做、复制及合并不退化到8位',async({browser})=>{
 const page=await pageFor(browser);try{const r=await page.evaluate(async()=>{const {D,P,E}= (window as any).A,d=D.createDocument(8,8,'16位历史',16),b=P.createBuffer(8,8,[128+1/257,16+2/257,32.5,255],16);d.layers=[D.createPixelLayer('16位',b)];d.activeLayerId=d.layers[0].id;E.openDocument(d);const before=Array.from(b.data);await E.commands.run('filterVignette',{amount:-5});await E.commands.run('undo');const undo=Array.from(E.api.activeLayer().pixels.data);await E.commands.run('redo');const redoType=E.api.activeLayer().pixels.data.constructor.name;await E.commands.run('copy');await E.commands.run('paste');const copyType=E.api.activeLayer().pixels.data.constructor.name;await E.commands.run('mergeDown');return{before,undo,redoType,copyType,mergeType:E.api.activeLayer().pixels.data.constructor.name,depth:E.api.doc.bitDepth};});expect(r.before).toEqual(r.undo);expect([r.redoType,r.copyType,r.mergeType]).toEqual(['Float32Array','Float32Array','Float32Array']);expect(r.depth).toBe(16);}finally{await page.close();}
});

test('16位文档可显示并明确导出为8位JPEG而不修改原像素',async({browser})=>{
 const page=await pageFor(browser);try{const r=await page.evaluate(async()=>{const {D,P,E,I}= (window as any).A,d=D.createDocument(8,8,'16位预览',16),b=P.createBuffer(8,8,[128+1/257,64.25,32.75,255],16);d.layers=[D.createPixelLayer('16位',b)];d.activeLayerId=d.layers[0].id;E.openDocument(d);const before=Array.from(b.data);const jpeg=await I.encodeImage(b,{format:'jpeg',quality:1,scale:1,background:[255,255,255]});return{type:jpeg.type,same:before.every((v:any,i:number)=>v===b.data[i]),depth:b.bitDepth};});expect(r).toEqual({type:'image/jpeg',same:true,depth:16});await expect(page.locator('canvas.main')).toBeVisible();}finally{await page.close();}
});

test('16位PSD导出导入通道与文件头一致，不暗中转为8位',async({browser})=>{
 const page=await pageFor(browser);try{const r=await page.evaluate(values=>{const {D,P,PSD}=(window as any).A,d=D.createDocument(4,1,'PSD16',16),b=P.createBuffer(4,1,undefined,16);for(let x=0;x<4;x++)b.data.set([values[x],64.25,32.75,200.5],x*4);d.layers=[D.createPixelLayer('16位像素',b)];d.activeLayerId=d.layers[0].id;const bytes=PSD.exportPsd(d),loaded=PSD.importPsd(bytes).document;return{bits:new DataView(bytes).getUint16(22),depth:loaded.bitDepth,original:Array.from(b.data),actual:Array.from(loaded.layers[0].pixels.data)};},values);expect(r.bits).toBe(16);expect(r.depth).toBe(16);r.original.forEach((v:any,i:number)=>expect(Math.abs(v-r.actual[i])).toBeLessThan(1/257));}finally{await page.close();}
});

test('新建16位画布后新增图层、文字、形状继承文档精度',async({browser})=>{
 const page=await pageFor(browser);try{await page.keyboard.press('Control+KeyN');const dialog=page.getByRole('dialog',{name:'新建画布'});await dialog.getByRole('combobox',{name:'位深'}).selectOption('16');await dialog.locator('input[type=number]').nth(0).fill('64');await dialog.locator('input[type=number]').nth(0).press('Tab');await dialog.locator('input[type=number]').nth(1).fill('64');await dialog.locator('input[type=number]').nth(1).press('Tab');await dialog.getByRole('button',{name:'创建',exact:true}).click();const r=await page.evaluate(async()=>{const {E}=(window as any).A;await E.commands.run('newLayer');return{depth:E.api.doc.bitDepth,types:E.api.doc.layers.map((l:any)=>l.pixels.data.constructor.name)};});expect(r).toEqual({depth:16,types:['Float32Array','Float32Array']});await tool(page,'shape');await gesture(page,[[10,10],[25,25]]);await tool(page,'type',{fontSize:12});await gesture(page,[[30,30]],{click:true});await page.getByRole('textbox',{name:'编辑画布文字'}).press('Control+Enter');const kinds=await page.evaluate(()=>(window as any).A.E.api.doc.layers.filter((l:any)=>l.shape||l.text).map((l:any)=>({type:l.pixels.data.constructor.name,depth:l.pixels.bitDepth})));expect(kinds).toEqual([{type:'Float32Array',depth:16},{type:'Float32Array',depth:16}]);}finally{await page.close();}
});

for(const operation of ['invert','mask','copy'])test('16位像素与透明度不被编辑路径舍入 '+operation,async({browser})=>{
 const page=await pageFor(browser);try{const r=await page.evaluate(async operation=>{const {E,D,P}=(window as any).A,d=D.createDocument(2,1,'低位精度',16),b=P.createBuffer(2,1,[128+1/257,64+2/257,32+3/257,200+1/257],16);d.layers=[D.createPixelLayer('16位',b)];d.activeLayerId=d.layers[0].id;E.openDocument(d);const before=Array.from(b.data);if(operation==='invert'){await E.commands.run('invertPixels');await E.commands.run('invertPixels');}else if(operation==='mask'){D.addLayerMask(E.api.activeLayer(),2,1);E.api.activeLayer().mask.pixels.data.fill(128);await E.commands.run('applyMask');}else{d.selection={...P.createMask(2,1,128),outline:null};await E.commands.run('copy');await E.commands.run('paste');}return{before,after:Array.from(E.api.activeLayer().pixels.data),depth:E.api.activeLayer().pixels.bitDepth};},operation);expect(r.depth).toBe(16);if(operation==='invert')r.after.forEach((v:any,i:number)=>expect(v).toBeCloseTo(r.before[i],4));else expect(r.after[3]).toBeCloseTo(r.before[3]*128/255,4);}finally{await page.close();}
});

test('16位TIFF保留最低有效位而非只保留高8位',async({browser})=>{
 const page=await pageFor(browser);try{ // @ts-ignore
 const {tiffFixture}=await import('../../scripts/audit/harness.mjs');const bytes=Buffer.from(tiffFixture({bitDepth:16,constant:128}),'base64');const offset=bytes.length-16*16*2;bytes.writeUInt16LE(128*257+1,offset);bytes.writeUInt16LE(128*257+2,offset+2);const r=await page.evaluate(async base64=>{const {I}=(window as any).A;const b=await I.decodeImageBytes(Uint8Array.from(atob(base64),c=>c.charCodeAt(0)).buffer);return{depth:b.bitDepth,first:b.data[0],second:b.data[4]};},bytes.toString('base64'));expect(r.depth).toBe(16);expect(r.second-r.first).toBeCloseTo(1/257,4);}finally{await page.close();}
});

test('16位蒙版创建、绘制历史和工程往返保留亚8位覆盖率',async({browser})=>{
 const page=await pageFor(browser);try{const r=await page.evaluate(async()=>{const {P,D,E,IO}=(window as any).A,d=D.createDocument(2,1,'16位蒙版',16),l=D.createPixelLayer('图像',P.createBuffer(2,1,[255,255,255,255],16));d.layers=[l];d.activeLayerId=l.id;E.openDocument(d);D.addLayerMask(l,2,1);l.mask.pixels.data[0]=128+1/257;l.mask.pixels.data[1]=128+2/257;l.mask.target='mask';const before=Array.from(l.mask.pixels.data);await E.commands.run('invertMask');await E.commands.run('undo');const undone=Array.from(E.api.activeLayer().mask.pixels.data);await IO.saveCompProject(E.api.doc,'/audit/project.comp');const loaded=await IO.loadCompProject('/audit/project.comp'),m=loaded.layers[0].mask.pixels;return{type:l.mask.pixels.data.constructor.name,before,undone,loaded:Array.from(m.data),depth:m.bitDepth};});expect(r.type).toBe('Float32Array');expect(r.depth).toBe(16);expect(r.undone).toEqual(r.before);expect(r.loaded[1]-r.loaded[0]).toBeCloseTo(1/257,4);}finally{await page.close();}
});

test('16位滤镜公开内核返回值保持有限且在0–255范围',async({page})=>{
 await page.goto('http://127.0.0.1:5194',{waitUntil:'networkidle'});const result=await page.evaluate(async()=>{ // @ts-ignore
 const C=await import('/src/core/filters/creative.ts'); // @ts-ignore
 const P=await import('/src/core/pixels.ts');const b=P.createBuffer(4,4,[250.25,240.5,230.75,255],16);C.applyBloom(b,{radius:1,intensity:100,threshold:0,color:[255,255,255],blendMode:'Add'});return Array.from(b.data);});expect(result.every(v=>Number.isFinite(v)&&v>=0&&v<=255)).toBe(true);
});
for(const mode of ['Multiply','Screen','Exclusion'])test('16位混合模式不使用整数查表截断 '+mode,async({browser})=>{
 const page=await pageFor(browser);try{const r=await page.evaluate(mode=>{const {D,P,C}=(window as any).A,d=D.createDocument(1,1,'混合16',16),b=D.createPixelLayer('底图',P.createBuffer(1,1,[128+1/257,64+2/257,32+3/257,255],16)),s=D.createPixelLayer('上图',P.createBuffer(1,1,mode==='Multiply'?[255,255,255,255]:[0,0,0,255],16));s.blendMode=mode;d.layers=[b,s];return{actual:Array.from(C.compositeDocument(d).buffer.data),expected:Array.from(b.pixels.data)};},mode);r.actual.forEach((v:any,i:number)=>expect(v).toBeCloseTo(r.expected[i],4));}finally{await page.close();}
});

for(const command of ['filterAddNoise','filterVignette','filterBloom','filterTonalContrast','filterLensCorrection','filterRemoveBackground','filterSharpen','filterDenoise','filterDither'])test('16位破坏性滤镜保留工作位深与有效数值 '+command,async({browser})=>{
 const page=await pageFor(browser);try{const r=await page.evaluate(async command=>{const {D,P,E}=(window as any).A,d=D.createDocument(12,12,'滤镜16',16),b=P.createBuffer(12,12,[128.25,64.5,32.75,255],16);d.layers=[D.createPixelLayer('像素',b)];d.activeLayerId=d.layers[0].id;E.openDocument(d);await E.commands.run(command);const out=E.api.activeLayer().pixels;return{depth:out.bitDepth,type:out.data.constructor.name,valid:Array.from(out.data).every((v:any)=>Number.isFinite(v)&&v>=0&&v<=255)};},command);expect(r).toEqual({depth:16,type:'Float32Array',valid:true});}finally{await page.close();}
});

test('8位图片导入16位文档后可高精度编辑，跨文档粘贴也继承位深',async({browser})=>{
 const page=await pageFor(browser);try{const r=await page.evaluate(async()=>{const {D,P,E}=(window as any).A,d=D.createDocument(16,16,'16位目标',16);d.layers=[D.createPixelLayer('底图',P.createBuffer(16,16,[20,30,40,255],16))];d.activeLayerId=d.layers[0].id;E.openDocument(d);await E.commands.run('openImage');const imported=E.api.activeLayer().pixels.data.constructor.name;const source=D.createDocument(2,2,'8位源'),layer=D.createPixelLayer('8位层',P.createBuffer(2,2,[128,64,32,255]));source.layers=[layer];source.activeLayerId=layer.id;E.openDocument(source);await E.commands.run('copy');E.selectDocument(1);await E.commands.run('paste');return{imported,pasted:E.api.activeLayer().pixels.data.constructor.name,depth:E.api.doc.bitDepth};});expect(r).toEqual({imported:'Float32Array',pasted:'Float32Array',depth:16});}finally{await page.close();}
});
