import fs from 'node:fs/promises';
import { launch,pageFor,tool,gesture,capture,saveJSON } from '../audit/harness.mjs';
// 修复后的UI合同：旧审计数据保持不变，迁移到正确入口时不再沿用旧按钮/直接执行断言。
const browser=await launch(),results=[];
async function run(id,title,fn){const page=await pageFor(browser);page.setDefaultTimeout(6000);let row={id,title,kind:'fix-ui'};try{Object.assign(row,await fn(page));row.status=row.pass?'通过':'失败';if(page.auditErrors.length){row.status='失败';row.errors=page.auditErrors;}}catch(e){row.status='失败';row.error=e.message;}finally{await page.close();}results.push(row);await saveJSON('ui-regressions.json',results);console.log(id,row.status,row.error??'');}
try{
 for(const kind of ['Levels','Curves','Gradient Map','Grain','Color Balance'])await run('UI-adjust-'+kind,'调整层真实参数编辑 '+kind,async p=>{await p.evaluate(kind=>window.A.E.commands.run('addAdjustment',kind),kind);const before=await capture(p);const controls=p.locator('.adjustment-controls');if(kind==='Gradient Map'){await controls.locator('input[type=color]').first().fill('#ff0000');}else if(kind==='Curves'){await controls.getByRole('button',{name:'添加点',exact:true}).click();await controls.locator('input[type=number]').last().fill('220');await controls.locator('input[type=number]').last().press('Tab');}else {const input=controls.locator('input[type=number]').first();await input.fill(kind==='Levels'?'50':'40');await input.press('Tab');}const after=await capture(p);await p.evaluate(()=>window.A.E.commands.run('undo'));const undo=await capture(p);return{pass:after.composite.hash!==before.composite.hash&&after.history>before.history&&undo.history<after.history,before:before.composite.hash,after:after.composite.hash,history:[before.history,after.history,undo.history]};});
 for(const [key,title]of [['stroke','描边'],['shadow','投影'],['innerShadow','内阴影'],['colorOverlay','颜色叠加'],['outerGlow','外发光'],['innerGlow','内发光']])await run('UI-effect-'+key,'图层效果UI修改 '+title,async p=>{const select=p.locator('.props .el-select').filter({has:p.locator('.el-select__placeholder').filter({hasText:'添加效果'})});await select.click();await p.locator('.el-select-dropdown__item:visible').getByText(title,{exact:true}).click();const field=p.locator('.effect-controls fieldset').filter({has:p.locator('legend').getByText(title,{exact:true})});const before=await capture(p);await field.locator('input[type=color]').fill('#00ffff');const after=await capture(p);return{pass:after.composite.hash!==before.composite.hash&&JSON.stringify(after.layers[1].effects[key].color)==='[0,255,255]',before:before.composite.hash,after:after.composite.hash,metadata:after.layers[1].effects[key]};});
 await run('UI-raw-groups','RAW缺失的四组实际修改并应用',async p=>{await p.evaluate(()=>{window.auditHost.openPath='/audit/input.dng';return window.A.E.commands.run('openRaw');});const before=await capture(p);for(const [title,value]of [['颜色混合','30'],['颜色分级','20'],['几何','2']]){const group=p.locator('.raw-group').filter({has:p.getByRole('heading',{name:title,exact:true})});await group.locator('input[type=number]').first().fill(value);await group.locator('input[type=number]').first().press('Tab');}const curve=p.locator('.raw-group').filter({has:p.getByRole('heading',{name:'曲线',exact:true})});await curve.getByRole('button',{name:'添加点'}).click();await curve.locator('input[type=number]').last().fill('190');await curve.locator('input[type=number]').last().press('Tab');await p.getByRole('button',{name:'应用',exact:true}).click();const after=await capture(p);return{pass:after.layers.at(-1).pixels.hash!==before.layers.at(-1).pixels.hash&&after.layers.at(-1).pixels.width===14&&after.dirty,before:before.layers.at(-1).pixels,after:after.layers.at(-1).pixels};});
 await run('UI-raw-filter','普通图层从菜单进入RAW滤镜并取消不修改',async p=>{const before=await capture(p);await p.locator('.menu-title').getByText('滤镜',{exact:true}).hover();await p.locator('.el-dropdown-menu:visible').getByText('相机RAW滤镜…',{exact:true}).click();const groups=await p.locator('.raw-controls .raw-group').count();await p.getByRole('button',{name:'取消',exact:true}).click();const after=await capture(p);return{pass:groups===8&&before.composite.hash===after.composite.hash,groups};});
 await run('UI-pixel-grid','菜单开关实际控制像素网格',async p=>{const before=await p.evaluate(()=>window.A.E.api.ui.pixelGrid);await p.locator('.menu-title').getByText('视图',{exact:true}).hover();await p.locator('.el-dropdown-menu:visible').getByText('显示像素网格',{exact:true}).click();const after=await p.evaluate(()=>window.A.E.api.ui.pixelGrid);return{pass:before!==after,before,after};});
 await run('UI-guides-lock','锁定参考线后不移动，解锁后可移动',async p=>{await p.evaluate(()=>{window.A.E.api.doc.guides=[{id:'line',axis:'vertical',position:10}];window.A.E.api.invalidate();});await p.keyboard.press('Control+Alt+Semicolon');await gesture(p,[[10,32],[14,32]]);const locked=await p.evaluate(()=>({locked:window.A.E.api.doc.guidesLocked,pos:window.A.E.api.doc.guides[0].position}));await p.keyboard.press('Control+Alt+Semicolon');await gesture(p,[[10,32],[14,32]]);const unlocked=await p.evaluate(()=>window.A.E.api.doc.guides[0].position);return{pass:locked.locked&&locked.pos===10&&unlocked===14,locked,unlocked};});
 await run('UI-layer-lock','图层锁定按钮控制画笔写入',async p=>{await p.locator('.layer-row').filter({hasText:'前景'}).getByTitle('锁定',{exact:true}).click();const before=await capture(p);await tool(p,'brush',{size:4});await gesture(p,[[22,22]],{click:true});const after=await capture(p);await p.locator('.layer-row').filter({hasText:'前景'}).getByTitle('解锁',{exact:true}).click();await gesture(p,[[22,22]],{click:true});const changed=await capture(p);return{pass:before.layers[1].pixels.hash===after.layers[1].pixels.hash&&changed.layers[1].pixels.hash!==before.layers[1].pixels.hash};});
 await run('UI-jpeg','原版JPEG快捷键选择正确格式与实时预览',async p=>{await p.keyboard.press('Control+Shift+Alt+KeyS');const dialog=p.locator('.el-dialog:visible');await dialog.getByAltText('实时预览').waitFor({state:'visible'});const text=await dialog.innerText();const images=await dialog.locator('img').count();return{pass:text.includes('JPEG')&&images===1,text,images};});
 await run('UI-filter-preview','滤镜菜单打开预览、取消保留源、应用可撤销',async p=>{const before=await capture(p);await p.locator('.menu-title').getByText('滤镜',{exact:true}).hover();await p.locator('.el-dropdown-menu:visible').getByText('渐晕',{exact:true}).click();const during=await capture(p);const count=await p.locator('.filter-editor input[type=number]').count();await p.getByRole('button',{name:'取消',exact:true}).click();const after=await capture(p);return{pass:during.dialog==='filterDialog'&&count>=4&&before.layers[1].pixels.hash===after.layers[1].pixels.hash&&before.history===after.history,count};});
 await run('UI-clipboard-flatten','剪贴板扁平化命令输出合并像素',async p=>{return p.evaluate(async()=>{const {E}=window.A;await E.commands.run('copy');await E.commands.run('flattenClipboard');await E.commands.run('paste');const l=E.api.activeLayer();return{pass:l.pixels.width===64&&l.pixels.height===64&&l.name==='粘贴的像素',size:[l.pixels.width,l.pixels.height],name:l.name};});});
 await run('UI-mask-history','独立蒙版移动后切回图像，再撤销不影响原图变换',async p=>{await p.evaluate(()=>{const {E,D}=window.A,l=E.api.activeLayer();D.addLayerMask(l,64,64);l.mask.linked=false;l.mask.placement={x:0,y:0,width:64,height:64};l.mask.target='mask';E.api.setToolOption('snap',false);});await gesture(p,[[32,32],[40,38]]);await p.evaluate(()=>{window.A.E.api.activeLayer().mask.target='image';return window.A.E.commands.run('undo');});return p.evaluate(()=>{const l=window.A.E.api.activeLayer();return{pass:l.transform.origin[0]===16&&l.transform.origin[1]===16&&l.mask.placement.x===0&&l.mask.placement.y===0,transform:l.transform,placement:l.mask.placement};});});
}finally{await browser.close();}
if(results.some(r=>r.status!=='通过'))process.exitCode=1;
