import { launch,pageFor,capture,saveJSON,tool,gesture } from '../audit/harness.mjs';
const browser=await launch(),results=[];
async function run(id,fn){const page=await pageFor(browser);let row={id,title:id,kind:'fix-workflow'};try{Object.assign(row,await fn(page));row.status=row.pass?'通过':'失败';if(page.auditErrors.length){row.status='失败';row.errors=page.auditErrors;}}catch(e){row.status='失败';row.error=e.message;}finally{await page.close();}results.push(row);console.log(row);}
try{
 await run('FIX-content-aware',async p=>{await p.evaluate(()=>{const {E,P}=window.A,m=P.createMask(64,64,0);for(let y=24;y<40;y++)for(let x=24;x<40;x++)m.data[y*64+x]=255;E.api.doc.selection={...m,outline:null};});const before=await capture(p);await p.keyboard.press('Shift+Delete');await p.getByRole('button',{name:'应用',exact:true}).click();const after=await capture(p);await p.keyboard.press('Control+KeyZ');const undo=await capture(p);return{pass:before.layers[1].pixels.hash!==after.layers[1].pixels.hash&&before.layers[1].pixels.hash===undo.layers[1].pixels.hash,before:before.layers[1].pixels.hash,after:after.layers[1].pixels.hash,undo:undo.layers[1].pixels.hash};});
 await run('FIX-snap-menu',async p=>{await p.locator('.menu-title').getByText('视图',{exact:true}).hover();await p.locator('.el-dropdown-menu:visible').getByText('吸附设置…',{exact:true}).click();return{pass:(await capture(p)).dialog==='snapSettings'};});
 await run('KEY-layer.group',async p=>{await p.locator('.layer-row').filter({hasText:'背景'}).click();await p.locator('.layer-row').filter({hasText:'前景'}).click({modifiers:['Shift']});await p.keyboard.press('Control+KeyG');const a=await capture(p);return{pass:a.layers.length===3&&a.layers.filter(l=>l.kind!=='group').every(l=>l.parent===a.layers.find(l=>l.kind==='group').id)};});
 await run('FIX-shift-keys',async p=>{await p.keyboard.press('Control+Shift+Semicolon');const snap=(await capture(p)).dialog==='snapSettings';await p.getByRole('button',{name:'关闭',exact:true}).click();await tool(p,'brush',{hardness:.5});await p.evaluate(()=>document.activeElement?.blur());await p.keyboard.press('Shift+BracketLeft');const a=await p.evaluate(()=>window.A.E.api.option('hardness',0));await p.keyboard.press('Shift+BracketRight');const b=await p.evaluate(()=>window.A.E.api.option('hardness',0));return{pass:snap&&Math.abs(a-.4)<1e-6&&Math.abs(b-.5)<1e-6,snap,a,b};});
 await run('UI-command-palette',async p=>{await p.keyboard.press('Control+KeyF');await p.getByRole('searchbox').fill('新建图层');await p.getByRole('searchbox').press('Enter');return{pass:(await capture(p)).layers.length===3};});
 await run('FIX-new-dialog',async p=>{await p.keyboard.press('Control+KeyN');const before=await capture(p);const numbers=p.locator('.el-dialog:visible input[type=number]');await numbers.nth(0).fill('80');await numbers.nth(0).press('Tab');await numbers.nth(1).fill('48');await numbers.nth(1).press('Tab');await p.getByRole('button',{name:'创建',exact:true}).click();const after=await capture(p);return{pass:before.dialog==='newCanvas'&&after.documents===2&&after.width===80&&after.height===48,actual:[after.width,after.height]};});
}finally{await browser.close();}
await saveJSON('workflow-regressions.json',results);if(results.some(r=>r.status!=='通过'))process.exitCode=1;
